AzureFunction-github-bot/AzureFunction-github-bot/GitHub-NanoFrameworkBot/run.csx

- to improve detection of possible and acceptable variations
- correct bug with flag setting
- improve comments to provide detailed informations on what are the problems and how the developer can correct the issues
Signed-off-by: José Simões <jose.simoes@eclo.solutions>

Improve code for obvious fix finding

---

AzureFunction-github-bot/AzureFunction-github-bot/GitHub-NanoFrameworkBot/run.csx

Signed-off-by: José Simões <jose.simoes@eclo.solutions>

Add synchronize action to pull request processing

---

EspFirmwareFlasher/Properties/AssemblyInfo.cs

because I want to have a new release for the EspFirmwareFlasher

Changed the version

---

github-actions/update-nf-dependencies.ps1

Ensure that "normal" CSProj packages are not included in dependency updates.
Also attempts to resolve XmlElements not being printed as a string value.
This could cause issues.

Add csproj filter to update dependencies script

---

github-actions/update-nf-dependencies.ps1

Environment variables were not working on certain repos. This is seemingly a github change.
It also fixes some minor errors.
* Properly displays XmlElements as strings.
* Allows NuGet.Config to be located in a different folder from root.
* Iterate over all solutions found in the repo.
* Be a little more verbose with output to ensure progress.
Required as dependency update is broken.
Tested on a fork against a new lib.

Fixes environment variables for nuget github action.

---

github-actions/update-nf-dependencies.ps1

This refactors the file so that it updates solutions efficiently.
It also fixes an issue where updating multiple dependencies at the same time will fail due to environment variables not supporting newlines.
Allows the samples repo to have auto dependency updates.
It was taking over 2 hours to update the samples repo. It now takes 25 minutes.
On a fork of the samples repo.
**Requires testing on a repo with out of date nuspec and NFMDP_PE_LoadHints some how**

Refactor update process.

---

github-actions/update-nf-dependencies.ps1

Work update dependencies ps1

---

azure-pipelines-templates/class-lib-package.yml

Addition to #35 for other scenario, now that the SNTP script has published to nuget.org. 
Will only happen on release, but easy to recognise if an issue occurs.

Add `.snupkg` to class-lib-package.yml

---

tools/VersionCop/Program.cs

Fixing issue with variable in nuspec version
- Fixing issue with variable in nuspec version
- See https://dev.azure.com/nanoframework/nanoframework.Logging/_build/results?buildId=27635&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997
- happens when using variables like $version$
on a real project (the logging one)

Fixing issue with variable in nuspec version

---

tools/VersionCop/Program.cs

Fix additional code on $version$ check in nugets
- Fix additional code on $version$ check in nugets

Fix nanovc additional code on $version$ check in nugets

---

tools/DependencyUpdater/Program.cs

- Removed "-Source" argument from nuget cli command
- Change "useNuGetConfig" to true for update
- One more additional check - include default "Source" arguments in nuget command if there is no nuget config and no sources specified in arguments 
- Fixes nanoFramework/Home#1098
- Tested locally on 3rd part repository with NuGet config file with custom repositories.
- PR created successfully
PR created by tool on 3rd party project (build failed due to a lot of changes in nanaoFramework packages - not related to nanodu)

Fix NuGet update command to include and use NuGet config file

---

tools/DependencyUpdater/Program.cs

- Replace hardcoded repository owner with parameter (already existing)
- Change how sln are stored inside repositories loop to prevent overriding repositories
- Be able to update packages in other organization

Repo owner and base branch are now taken from parameters

---

tools/DependencyUpdater/DependencyUpdater.Tests/ProgramTests.cs
tools/DependencyUpdater/Program.cs

- New parameter "useGitTokenForClone"
- Based on passed parameters, tool now decide what URL should be used for cloning (with PAT or without) and which PAT should be used.
- git command with PAT vs without tested on custom AZDO pipeline
- nanodu tested via new unit tests (will be tested ASAP in real pipeline after new version release)

Allow clone from private git repositories via PAT

---

tools/Profiler/NanoProfiler/Profiler/ProfilerPackets.cs

- Add null check for LogText in profiler packet processors.
- Running without profiler trace would break the application
- Part of nanoFramework/Home#1354.

[Profiler] Add null check for LogText in profiler packet processors

---

tools/Profiler/NanoProfiler/ViewModels/ProfilerLauncherViewModel.cs

- Log file from temp folder is now created with correct extension.
- Part of nanoFramework/Home#1354

[Profiler] Fix log file extension

---

tools/Profiler/NanoProfiler/ViewModels/ProfilerLauncherViewModel.cs
tools/Profiler/NanoProfiler/Views/ProfilerLauncherView.xaml
tools/Profiler/NanoProfiler/Views/ProfilerLauncherView.xaml.cs

An issue with the debug/trace logging in the GUI was no limit on the # of messages saved to simple text box + appending on every message event receipt. As the text grows, so does memory and time to update. Also marshaling all of those individual UI updates for each event msg onto the U thread is too slow. Change was to switch to keeping only last 1000 messages and using a timer to update the UI thread.
Since these messages are truncated in the GUI, a log file is now auto created based on the profile data filename.
I also made various XAML improvements, key being the log area scales as GUI is resized.
See above.
I ran the tool, sometimes specifying the data filename, sometime not (temp file).

[Profiler]Improve debug/trace performance in GUI + log these messages to file

---

tools/Profiler/NanoProfiler/Views/ShellWindow.xaml
tools/Profiler/NanoProfiler/Views/ShellWindow.xaml.cs

- Fix behaviour of Maximize and Restore buttons .

[Profiler] Fix behaviour of Maximize and Restore buttons

---

tools/Profiler/NanoProfiler/Views/ShellWindow.xaml
tools/Profiler/NanoProfiler/Views/ShellWindow.xaml.cs

Add  Resize grip in Window

---

tools/Profiler/NanoProfiler/Settings/SettingsView.xaml
tools/Profiler/NanoProfiler/Views/ProfilerLauncherView.xaml
tools/Profiler/NanoProfiler/Views/ShellWindow.xaml

[Profiler] Attempt to  use  more slick and simple style

---

.github/workflows/NanoFramework-GitHubBot.yml
.github/workflows/check-package-lock.yml
.github/workflows/check-packages-updated.yml
.github/workflows/keep-repo-active.yml
.github/workflows/update-dependencies.yml

mainly due to Node V20
Keeps them up-to-date

Update Github Actions

---

github-nfbot/GitHub-nfbot/GitHub-nfbot.csproj

Updates the project file to use the latest LTS release .Net 8 as .Net 6 is deprecated.
follows changes in #85 
The project should use the latest LTS version of the .net framework.
Untested!

[github-nfbot] update project framework version
